### ISSUE TITLE
Allow to use empty string as a valid value

### ISSUE THREAD

**Issue by dnagir** [cultureamp/cfparams#8]
Currently it appears that `cfparams` does not allow empty values to be passed as parameters.

Example:

```
# parameters file
BugsnagApiKey: "" # TODO: Ignore for development account
```

```
# partial tempalte file:
Parameters:
  BugsnagApiKey:
    Description: API Key for Bugsnag error reporting
    Type: String
```

Executed with the arguments:

```
  cfparams \
    --template cloudformation.yml \
    --parameters "$PARAMS_FILE" \
    --accept-defaults \
    --no-previous
```

The error:

```
An error occurred (ValidationError) when calling the CreateStack operation: ParameterValue for ParameterKey BugsnagApiKey is required
```

The produced output for that key:

```
  {
    "ParameterKey": "BugsnagApiKey"
  }
```
